# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Bug fixes 🛠
      labels:
        - bug
        - fix
    - title: Other Changes
      labels:
        - '*'
